# ${project.name} config
host: 0.0.0.0
port: 5555
voteInterval: 86400
rewards:
  - give {0} diamond 5
  - give {0} stone 128
randomReward: false
checkIP: true
nagInterval: 300
nag: '&eHey {0} we noticed you have not yet voted for us today. Please do so at md-5.net'
broadcastMessage: '&5 {0} voted for the server, you can too at md-5.net'
notOnline: You are not online
wrongIP: The player you have selected does not have the same ip as you
tooSoon: You have already voted in the last 24 hours
thanks: Thanks for voting using Vote4Diamondz by md_5. Your vote is appreciated.
