name: Vote4Diamondz
version: 2.0
description: Bukkit plugin to automatically give people rewards for voting via custom php script.
author: md_5
website: https://github.com/Shadowraze/Vote4Diamndz

main: com.md_5.vote4diamondz.Vote4Diamondz

commands:
    votes:
        description: View the top 3 voting players
        permission: vote4diamondz.votes

permissions:
    vote4diamondz.votes:
        description: Allows use of the top votes command
        default: true
    vote4diamondz.votes.clear:
        description: Allows the clearing of votes
        default: op